In [6]:
import pandas as pd

df = pd.read_csv("/pisa_lectura_limpia.csv")

df.head()

,pais_economia,anio,puntaje_lectura,bajo_nivel_2_pct,nivel_5_o_superior_pct
0,Argentina,2022,400.74404,54.50786,0.95752
1,Argentina,2025,388.70426,59.56992,0.63042
2,Armenia,2025,348.28569,81.01475,0.01112
3,Australia,2022,498.05094,21.19190,12.37921
4,Australia,2025,490.86328,23.37189,11.15283

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 165 entries, 0 to 164
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   pais_economia           165 non-null    object
 1   anio                    165 non-null    int64
 2   puntaje_lectura         165 non-null    float64
 3   bajo_nivel_2_pct        165 non-null    float64
 4   nivel_5_o_superior_pct  165 non-null    float64
dtypes: float64(3), int64(1), object(1)
memory usage: 6.6+ KB

In [8]:
df.isnull().sum()

pais_economia             0
anio                      0
puntaje_lectura           0
bajo_nivel_2_pct          0
nivel_5_o_superior_pct    0
dtype: int64

In [9]:
chile = df[df["pais_economia"] == "Chile"]

chile

,pais_economia,anio,puntaje_lectura,bajo_nivel_2_pct,nivel_5_o_superior_pct
21,Chile,2022,447.97896,33.72691,2.48577
22,Chile,2025,435.65582,38.17916,1.77870

In [11]:
chile_2022 = chile[chile["anio"] == 2022].iloc[0]
chile_2025 = chile[chile["anio"] == 2025].iloc[0]

cambio_puntaje = chile_2025["puntaje_lectura"] - chile_2022["puntaje_lectura"]
cambio_bajo_nivel_2 = chile_2025["bajo_nivel_2_pct"] - chile_2022["bajo_nivel_2_pct"]
cambio_nivel_5 = chile_2025["nivel_5_o_superior_pct"] - chile_2022["nivel_5_o_superior_pct"]

print("Cambio en puntaje de lectura:", round(cambio_puntaje, 2))
print("Cambio bajo Nivel 2:", round(cambio_bajo_nivel_2, 2), "puntos porcentuales")
print("Cambio Nivel 5 o superior:", round(cambio_nivel_5, 2), "puntos porcentuales")

Cambio en puntaje de lectura: -12.32
Cambio bajo Nivel 2: 4.45 puntos porcentuales
Cambio Nivel 5 o superior: -0.71 puntos porcentuales

In [12]:
pisa_2025 = df[df["anio"] == 2025]

comparacion_2025 = pisa_2025[
    ["pais_economia", "puntaje_lectura", "bajo_nivel_2_pct", "nivel_5_o_superior_pct"]
].sort_values("puntaje_lectura", ascending=False)

comparacion_2025

,pais_economia,puntaje_lectura,bajo_nivel_2_pct,nivel_5_o_superior_pct
138,Singapore,534.90002,14.08448,21.87349
8,B-S-J-Z (China),526.51825,7.29856,10.32003
24,Chinese Taipei,507.78799,17.92845,13.43356
72,Japan,502.71450,18.55046,11.18601
91,Macao (China),501.05358,15.29858,7.21559
...,...,...,...,...
164,Zambia,324.87812,82.34033,0.00000
106,Morocco,321.12710,87.17691,0.00121
77,Kenya,320.21398,88.91221,0.00000
82,Kurdistan Region (Iraq),311.53031,93.18299,0.00174
132,Rwanda,300.94391,96.15009,0.00000